- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
    - Medical
    - Chemistry
    - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
<<<<<<< HEAD
  storage:
    back:
    - BoxSurvivalMedical
=======
  #storage:
    #back:
    #- Stuff
>>>>>>> ba39b6f5512c2befcf7263a1a6a2922339ed5c16
