using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

// AXOLOTL: Imports for ghostrespawn
using Robust.Shared.Timing;
using Robust.Shared.Configuration;
using Content.Shared.CCVar;
using Content.Client._AXOLOTL.RespawnButton;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;

    // AXOLOTL: Respawn button
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IConfigurationManager _configurationManager = default!;

    private TimeSpan? _AxolotlTimeOfDeath;
    private float _AxolotlMinTimeToRespawn;
    public GhostRespawnRulesWindow AxolotlGhostRespawnRulesWindow { get; }
    public event Action? AxolotlGhostRespawnPressed;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();

        // AXOLOTL: Ghostrespawn
        AxolotlGhostRespawnRulesWindow = new GhostRespawnRulesWindow();
        AxolotlGhostRespawnRulesWindow.RespawnButton.OnPressed += _ => AxolotlGhostRespawnPressed?.Invoke();
        AxolotlGhostRespawnButton.OnPressed += _ => AxolotlGhostRespawnRulesWindow.OpenCentered();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    // AXOLOTL: Set time of death info
    public void Update(int? roles, bool? canReturnToBody, TimeSpan? timeOfDeath, float minTimeToRespawn)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        _AxolotlTimeOfDeath = timeOfDeath;
        _AxolotlMinTimeToRespawn = minTimeToRespawn;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));
            if (roles > 0)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }
            else
            {
                GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
            }
        }

        TargetWindow.Populate();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }

    // AXOLOTL: Required to make the ghost respawn timer tick
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_AxolotlTimeOfDeath is null)
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", "disabled"));
            AxolotlGhostRespawnButton.Disabled = true;
            return;
        }

        var delta = (_AxolotlMinTimeToRespawn - _gameTiming.CurTime.Subtract(_AxolotlTimeOfDeath.Value).TotalSeconds);
        if (delta <= 0)
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-allowed");
            AxolotlGhostRespawnButton.Disabled = false;
        }
        else
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", $"{delta:f1}"));
            AxolotlGhostRespawnButton.Disabled = true;
        }
    }

    public void AxolotlUpdateRespawn(TimeSpan? todd)
    {
        if (todd != null)
        {
            _AxolotlTimeOfDeath = todd;
            _AxolotlMinTimeToRespawn = _configurationManager.GetCVar(CCVars.RespawnTime);
        }
    }
}
