name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to axolotl
      uses: appleboy/scp-action@master
      with:
        host: axolotl.yuniiworks.de
        username: builds-the-server
        key: ${{ secrets.PUSH }}
        source: "release/${{ github.sha }}"
        target: "/home/builds-the-server/cdn/builds/"
        strip_components: 1

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: axolotl.yuniiworks.de
        username: builds-the-server
        key: ${{ secrets.PUSH }}
        script: /home/builds-the-server/push.ps1 ${{ github.sha }}
